"""Export a conversation transcript to a local PDF (Block 1 requirement).

Renders the stored display transcript (user questions, assistant answers and
their source citations) into a PDF saved locally under ``EXPORT_DIR``. Kannada
answers are rendered with the Windows 'Nirmala UI' font (falls back to Helvetica
if unavailable, e.g. on a non-Windows host).
"""
from __future__ import annotations

import os
from pathlib import Path

from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from app.core.logging import get_logger

logger = get_logger("chat.pdf")

EXPORT_DIR = Path("exports")
_UNICODE_FONT = "CrimeRakshakUnicode"
_FONT_REGISTERED: bool | None = None


def _ensure_font() -> str:
    """Register a Kannada-capable Unicode font once; return its name (or Helvetica)."""
    global _FONT_REGISTERED
    if _FONT_REGISTERED is True:
        return _UNICODE_FONT
    if _FONT_REGISTERED is False:
        return "Helvetica"

    candidates = [
        (r"C:\Windows\Fonts\Nirmala.ttc", 0),
        (r"C:\Windows\Fonts\NirmalaUI.ttf", None),
        ("/usr/share/fonts/truetype/noto/NotoSansKannada-Regular.ttf", None),
    ]
    for path, sub in candidates:
        if os.path.exists(path):
            try:
                kwargs = {"subfontIndex": sub} if sub is not None else {}
                pdfmetrics.registerFont(TTFont(_UNICODE_FONT, path, **kwargs))
                _FONT_REGISTERED = True
                return _UNICODE_FONT
            except Exception as exc:  # pragma: no cover
                logger.warning("could not register font %s: %s", path, exc)
    _FONT_REGISTERED = False
    return "Helvetica"


def _esc(text: str) -> str:
    return (text or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def export_conversation(conversation_id: str, transcript: list[dict],
                        username: str | None = None) -> Path:
    """Render a transcript to a PDF file and return its path.

    ``transcript`` is a list of ``{role, text, sources?, language?}`` dicts.
    """
    EXPORT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = EXPORT_DIR / f"conversation_{conversation_id}.pdf"

    font = _ensure_font()
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Title"], fontName=font)
    q_style = ParagraphStyle("Q", parent=styles["Normal"], fontName=font,
                             fontSize=11, leading=15, spaceBefore=8,
                             textColor="#1a3c6e", alignment=TA_LEFT)
    a_style = ParagraphStyle("A", parent=styles["Normal"], fontName=font,
                             fontSize=10.5, leading=15, spaceBefore=4)
    src_style = ParagraphStyle("Src", parent=styles["Italic"], fontName=font,
                              fontSize=7.5, leading=10, textColor="#666666",
                              spaceBefore=2, leftIndent=8)

    story = [
        Paragraph("CrimeRakshak — Conversation Transcript", title_style),
        Paragraph(f"Conversation ID: {_esc(conversation_id)}", styles["Normal"]),
    ]
    if username:
        story.append(Paragraph(f"User: {_esc(username)}", styles["Normal"]))
    story.append(Spacer(1, 6 * mm))

    for turn in transcript:
        role = turn.get("role")
        text = _esc(turn.get("text", ""))
        if role == "user":
            story.append(Paragraph(f"<b>Q:</b> {text}", q_style))
        else:
            story.append(Paragraph(f"<b>A:</b> {text}", a_style))
            for src in turn.get("sources", []) or []:
                story.append(Paragraph(f"↳ source: {_esc(src)}", src_style))

    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph(
        "Generated by CrimeRakshak. Figures are grounded in the cited sources; "
        "case-level results may use synthetic demonstration data.",
        src_style,
    ))

    SimpleDocTemplate(str(out_path), pagesize=A4,
                     leftMargin=18 * mm, rightMargin=18 * mm,
                     topMargin=16 * mm, bottomMargin=16 * mm).build(story)
    logger.info("exported conversation %s -> %s", conversation_id, out_path)
    return out_path
